id: I25329E32
ocr_import_info:
  timestamp: '2023-09-27T14:27:17.642259+00:00'
  batch_id: batch-a603
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 15:31:54.178773+00:00
last_modified: 2023-09-27 15:31:54.178780+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3736
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3736
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པའི་མཛོད་ཀྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ཉིན་བྱེད་དབང་པོའི་སྣང་བ།
  languages:
  - bo
  author: རྒྱལ་དབང་ཆོས་རྗེ་བློ་བཟང་འཕྲིན་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9106702523673835
  ocr_word_median_confidence_index: 0.96486294
bases:
  I1NLM3736_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3736_001
      total_pages: 597
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3736_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.96486294
      ocr_word_mean_confidence_index: 0.9106702523673835
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
